Repository tmforum-oda/oda-ca-docs, pull requests merged in 2023-01, with the labels that each got.

#90 Playbook refresh
  Playbook.md
Labels: documentation

#92 Added a custom .css to over-ride bullet-lists
  doc/_static/css/custom.css
  doc/caDocs/Getting_started.md
  doc/caDocs/Playbook.md
  doc/conf.py
Labels: bug-fix

#93 Updated the custom css to fix UL style issue.
  doc/_static/css/custom.css
Labels: bug-fix

#95 Upgraded example Product Catalog component to v1beta1
  doc/_static/css/custom.css
  examples/ProductCatalog/productcatalog/templates/component-productcatalog.yaml
Labels: feature
